repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
    -   id: flake8
        args:
        - --ignore=E111,E114,E501
        #:- --per-file-ignores='examples/kalman/sympy_helpers.py:E241'
        - --statistics
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --disable=R,C,W
