repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
    -   id: flake8
        args:
        - --select=F
-   repo: https://github.com/PyCQA/pylint
    rev: master
    hooks:
    -   id: pylint
        args:
        - --disable=R,C,W
# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         args:
#         - --disable=R,C,W
#         - --init-hook="import sys; sys.path.insert(0, './modules'); print(123)"
