repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
        exclude: /kalman/
-   repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
    -   id: flake8
        exclude: /kalman/
        args:
        - --select=F
-   repo: local
    hooks:
    -   id: pylint
        exclude: /kalman/
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --disable=R,E,I,C,W
                    
